
define(['text!../sprites/agent.json',
        'text!../sprites/arrow.json',
        'text!../sprites/axe.json',
        'text!../sprites/bat.json',
        'text!../sprites/beachnpc.json',
        'text!../sprites/bluesword.json',
        'text!../sprites/boss.json',
        'text!../sprites/chest.json',
        'text!../sprites/clotharmor.json',
        'text!../sprites/clotharmor2.json', //SRR
        'text!../sprites/coder.json',
        'text!../sprites/crab.json',
        'text!../sprites/death.json',
        'text!../sprites/deathknight.json',
        'text!../sprites/quester01.json',
        'text!../sprites/gite01.json',  //SRR
        'text!../sprites/gite02.json',
        'text!../sprites/gite03.json',
        'text!../sprites/gite04.json',
        'text!../sprites/gite05.json',  
        'text!../sprites/gite06.json',
        'text!../sprites/gite07.json',
        'text!../sprites/gite08.json',
        'text!../sprites/gite09.json',
        'text!../sprites/gite10.json',
        'text!../sprites/villager01.json',  //SRR
        'text!../sprites/villager02.json',
        'text!../sprites/villager03.json',
        'text!../sprites/villager04.json',
        'text!../sprites/villager05.json',  
        'text!../sprites/villager06.json',
        'text!../sprites/villager07.json',
        'text!../sprites/villager08.json',
        'text!../sprites/villager09.json',
        'text!../sprites/villager10.json',
        'text!../sprites/eye.json',
        'text!../sprites/firefox.json',
        'text!../sprites/forestnpc.json',
        'text!../sprites/goblin.json',
        'text!../sprites/goldenarmor.json',
	'text!../sprites/goldenarmor2.json', //SRR
        'text!../sprites/goldensword.json',
        'text!../sprites/guard.json',
        'text!../sprites/hand.json',
        'text!../sprites/impact.json',
        'text!../sprites/item-axe.json',
        'text!../sprites/item-bluesword.json',
        'text!../sprites/item-burger.json',
        'text!../sprites/item-cake.json',
        'text!../sprites/item-firepotion.json',
        'text!../sprites/item-flask.json',
        'text!../sprites/item-goldenarmor.json',
        'text!../sprites/item-goldensword.json',
        'text!../sprites/item-leatherarmor.json',
        'text!../sprites/item-mailarmor.json',
        'text!../sprites/item-morningstar.json',
        'text!../sprites/item-platearmor.json',
        'text!../sprites/item-redarmor.json',
        'text!../sprites/item-redsword.json',
        'text!../sprites/item-sword1.json',
        'text!../sprites/item-sword2.json',
        'text!../sprites/king.json',
        'text!../sprites/malade01.json',
        'text!../sprites/trap1.json',
        'text!../sprites/lore01.json',
        'text!../sprites/lore02.json',
        'text!../sprites/leatherarmor.json',
        'text!../sprites/leatherarmor2.json', //SRR
        'text!../sprites/loot.json',
        'text!../sprites/mailarmor.json',
        'text!../sprites/mailarmor2.json', //SRR
        'text!../sprites/morningstar.json',
        'text!../sprites/nyan.json',
        'text!../sprites/octocat.json',
        'text!../sprites/ogre.json',
        'text!../sprites/platearmor.json',
	'text!../sprites/platearmor2.json',
        'text!../sprites/quester03.json',
        'text!../sprites/rat.json',
        'text!../sprites/rat2.json',
        'text!../sprites/redarmor.json',
	'text!../sprites/redarmor2.json', //SRR
        'text!../sprites/redsword.json',
        'text!../sprites/rick.json',
        'text!../sprites/quester04.json',
        'text!../sprites/shadow16.json',
        'text!../sprites/skeleton.json',
        'text!../sprites/skeleton2.json',
        'text!../sprites/snake.json',
        'text!../sprites/quester05.json',
        'text!../sprites/sparks.json',
        'text!../sprites/spectre.json',
        'text!../sprites/sword.json',
        'text!../sprites/sword1.json',
        'text!../sprites/sword2.json',
        'text!../sprites/talk.json',
        'text!../sprites/target.json',
        'text!../sprites/quester02.json',
        'text!../sprites/villager.json',
        'text!../sprites/wizard.json',
        'text!../sprites/pface_boy1.json', //SRR
        'text!../sprites/pface_boy2.json',
        'text!../sprites/pface_boy3.json',
        'text!../sprites/pface_girl1.json',
        'text!../sprites/pface_girl2.json',
        'text!../sprites/pface_girl3.json'], function() {

    var sprites = {};

    _.each(arguments, function(spriteJson) {
        var sprite = JSON.parse(spriteJson);

        sprites[sprite.id] = sprite;
    });

    return sprites;
});
